name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */24 * * *" 
  workflow_dispatch:

jobs:
  # build:
  #   name: Jobs to update datas
  #   runs-on: ubuntu-latest
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Snake Animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        # id: snake-gif
        with:
          github_user_name: anaperola
          # svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
